# Generated by Django 3.2.16 on 2024-07-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20240729_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
    ]
